<a href="https://colab.research.google.com/github/raghavharshita/Colab-Files-Notes/blob/main/Encoding_Categorical_Variables.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Ordinal Encoding

In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv('/content/customer FREE (2).csv').drop(columns=['age','gender'])
df.head()

review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [3]:
from sklearn.preprocessing import OrdinalEncoder
from sklearn.model_selection import train_test_split

In [4]:
oe=OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])
x_train,x_test,y_train,y_test=train_test_split(df.iloc[:,:-1],df.iloc[:,-1],test_size=0.2)

In [5]:
x_train=oe.fit_transform(x_train)
x_test=oe.transform(x_test)

In [6]:
x_train

array([[2., 0.],
       [0., 2.],
       [2., 1.],
       [0., 0.],
       [0., 1.],
       [2., 2.],
       [0., 2.],
       [2., 2.],
       [2., 0.],
       [0., 2.],
       [2., 0.],
       [2., 2.],
       [2., 0.],
       [0., 2.],
       [1., 0.],
       [1., 1.],
       [0., 2.],
       [2., 0.],
       [1., 0.],
       [1., 1.],
       [0., 0.],
       [0., 0.],
       [1., 2.],
       [1., 0.],
       [2., 1.],
       [2., 2.],
       [0., 1.],
       [2., 1.],
       [2., 0.],
       [0., 1.],
       [1., 0.],
       [0., 0.],
       [0., 1.],
       [1., 1.],
       [1., 0.],
       [1., 1.],
       [2., 2.],
       [1., 1.],
       [1., 1.],
       [0., 2.]])

In [7]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [8]:
oe.feature_names_in_

array(['review', 'education'], dtype=object)

In [9]:
oe.n_features_in_

2

In [10]:
oe.inverse_transform(np.array([0,2]).reshape(1,2))

array([['Poor', 'PG']], dtype=object)

In [11]:
oe.get_feature_names_out()

array(['review', 'education'], dtype=object)

In [12]:
oe=OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']],handle_unknown='use_encoded_value',unknown_value=-1)

In [13]:
x_train,x_test,y_train,y_test=train_test_split(df.iloc[:,:-1],df.iloc[:,-1],test_size=0.2)
x_train=oe.fit_transform(x_train)
x_test=oe.transform(x_test)
oe.transform(np.array(['Poor','College']).reshape(1,2))

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(


array([[ 0., -1.]])

In [15]:
# handling infrequent categories
x=np.array([['dog']*5+['cat']*20+['rabbit']*10+['snake']*3],dtype=object).T
x

array([['dog'],
       ['dog'],
       ['dog'],
       ['dog'],
       ['dog'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['rabbit'],
       ['rabbit'],
       ['rabbit'],
       ['rabbit'],
       ['rabbit'],
       ['rabbit'],
       ['rabbit'],
       ['rabbit'],
       ['rabbit'],
       ['rabbit'],
       ['snake'],
       ['snake'],
       ['snake']], dtype=object)

In [16]:
oe=OrdinalEncoder(max_categories=3).fit(x)

In [17]:
oe.infrequent_categories_

[array(['dog', 'snake'], dtype=object)]

In [18]:
oe.transform(np.array(['cat','rabbit','snake','dog']).reshape(4,1))

array([[0.],
       [1.],
       [2.],
       [2.]])

In [21]:
enc=OrdinalEncoder(min_frequency=4).fit(x)
enc.infrequent_categories_

[array(['snake'], dtype=object)]

In [26]:
data=[['cat'],[np.nan],['Dog'],['Fish'],[np.nan]]
encoder=OrdinalEncoder(encoded_missing_value=-1)
encoder_data=encoder.fit_transform(data)
print(encoder_data)

[[ 2.]
 [-1.]
 [ 0.]
 [ 1.]
 [-1.]]


## Label Encoding

In [27]:
df.head()

review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [28]:
x_train,x_test,y_train,y_test=train_test_split(df.iloc[:,:-1],df.iloc[:,-1],test_size=0.2)

In [30]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y_train=le.fit_transform(y_train)
y_test=le.fit_transform(y_test)

In [31]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [32]:
le.inverse_transform(np.array([1,1,0]))

array(['Yes', 'Yes', 'No'], dtype=object)

## One Hot Encoding

In [86]:
import pandas as pd
import numpy as np
cars=pd.read_csv('/content/cars FREE.csv').drop(columns=['km_driven','owner'])
cars.head()

brand    fuel  selling_price
0   Maruti  Diesel         450000
1    Skoda  Diesel         370000
2    Honda  Petrol         158000
3  Hyundai  Diesel         225000
4   Maruti  Petrol         130000

In [87]:
x=cars.iloc[:,:-1]
y=cars.iloc[:,-1]

In [88]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [89]:
x_train['brand'].nunique(),x_train['fuel'].nunique()

(30, 4)

In [69]:
from sklearn.preprocessing import OneHotEncoder
ohe=OneHotEncoder()
x_train=ohe.fit_transform(x_train).toarray()

In [93]:
x_train.shape

(6502, 34)

In [92]:
ohe.categories_

[array(['Ambassador', 'Audi', 'BMW', 'Chevrolet', 'Daewoo', 'Datsun',
        'Fiat', 'Force', 'Ford', 'Honda', 'Hyundai', 'Isuzu', 'Jaguar',
        'Jeep', 'Kia', 'Land', 'Lexus', 'MG', 'Mahindra', 'Maruti',
        'Mercedes-Benz', 'Mitsubishi', 'Nissan', 'Opel', 'Renault',
        'Skoda', 'Tata', 'Toyota', 'Volkswagen', 'Volvo'], dtype=object),
 array(['CNG', 'Diesel', 'LPG', 'Petrol'], dtype=object)]

In [94]:
ohe.feature_names_in_

array(['brand', 'fuel'], dtype=object)

In [95]:
ohe.get_feature_names_out()

array(['brand_Ambassador', 'brand_Audi', 'brand_BMW', 'brand_Chevrolet',
       'brand_Daewoo', 'brand_Datsun', 'brand_Fiat', 'brand_Force',
       'brand_Ford', 'brand_Honda', 'brand_Hyundai', 'brand_Isuzu',
       'brand_Jaguar', 'brand_Jeep', 'brand_Kia', 'brand_Land',
       'brand_Lexus', 'brand_MG', 'brand_Mahindra', 'brand_Maruti',
       'brand_Mercedes-Benz', 'brand_Mitsubishi', 'brand_Nissan',
       'brand_Opel', 'brand_Renault', 'brand_Skoda', 'brand_Tata',
       'brand_Toyota', 'brand_Volkswagen', 'brand_Volvo', 'fuel_CNG',
       'fuel_Diesel', 'fuel_LPG', 'fuel_Petrol'], dtype=object)

In [96]:
ohe.n_features_in_

2

In [97]:
pd.DataFrame(x_train,columns=ohe.get_feature_names_out())

brand_Ambassador  brand_Audi  brand_BMW  brand_Chevrolet  brand_Daewoo  \
0                    0           0          0                0             0   
1                    0           0          0                0             0   
2                    0           0          0                0             0   
3                    0           0          0                0             0   
4                    0           0          0                0             0   
...                ...         ...        ...              ...           ...   
6497                 0           0          0                0             0   
6498                 0           0          0                0             0   
6499                 0           0          0                0             0   
6500                 0           0          0                0             0   
6501                 0           0          1                0             0   

      brand_Datsun  brand_Fiat  brand_Force  brand_Ford  brand_Honda  ...  \
0                0           0            0           0            1  ...   
1                0           0            0           0            0  ...   
2                0           0            0           0            0  ...   
3                0           0            0           0            0  ...   
4                0           0            0           0            0  ...   
...            ...         ...          ...         ...          ...  ...   
6497             0           0            0           0            0  ...   
6498             0           0            0           0            0  ...   
6499             0           0            0           0            0  ...   
6500             0           0            0           0            0  ...   
6501             0           0            0           0            0  ...   

      brand_Renault  brand_Skoda  brand_Tata  brand_Toyota  brand_Volkswagen  \
0                 0            0           0             0                 0   
1                 0            0           0             0                 0   
2                 0            0           0             1                 0   
3                 0            0           0             0                 0   
4                 0            0           0             0                 0   
...             ...          ...         ...           ...               ...   
6497              0            0           0             0                 0   
6498              0            0           0             0                 0   
6499              0            0           0             0                 0   
6500              0            0           1             0                 0   
6501              0            0           0             0                 0   

      brand_Volvo  fuel_CNG  fuel_Diesel  fuel_LPG  fuel_Petrol  
0               0         0            0         0            1  
1               0         0            0         0            1  
2               0         0            0         0            1  
3               0         0            0         0            1  
4               0         0            1         0            0  
...           ...       ...          ...       ...          ...  
6497            0         0            1         0            0  
6498            0         0            0         0            1  
6499            0         0            0         0            1  
6500            0         0            0         0            1  
6501            0         0            1         0            0  

[6502 rows x 34 columns]

In [98]:
ohe.inverse_transform(np.array([0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,1.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,1.]).reshape(1,34))

array([['Hyundai', 'Petrol']], dtype=object)

In [90]:
#spare output false -> we are not to apply toarray() after .fit_transform()
ohe=OneHotEncoder(sparse_output=False,dtype=np.int32)
x_train=ohe.fit_transform(x_train)
x_train

array([[0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 1],
       ...,
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 1, ..., 1, 0, 0]], dtype=int32)

In [99]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
ohe=OneHotEncoder(drop='first',sparse_output=False)
ohe.fit_transform(x_train).shape

(6502, 34)

In [100]:
ohe.drop_idx_

array([0, 0], dtype=object)

In [110]:
#handling rare categories
x_train['brand'].value_counts()

brand
Maruti           1953
Hyundai          1127
Mahindra          635
Tata              586
Toyota            391
Honda             369
Ford              320
Chevrolet         185
Renault           183
Volkswagen        154
BMW                96
Skoda              82
Nissan             62
Jaguar             59
Volvo              54
Datsun             48
Mercedes-Benz      43
Fiat               35
Audi               30
Jeep               26
Lexus              22
Mitsubishi         13
Force               6
Land                5
Kia                 4
Daewoo              3
MG                  3
Ambassador          3
Isuzu               2
Ashok               1
Peugeot             1
Opel                1
Name: count, dtype: int64

In [107]:
x_train['fuel'].value_counts()

fuel
Diesel    3545
Petrol    2880
CNG         46
LPG         31
Name: count, dtype: int64

In [103]:
ohe=OneHotEncoder(sparse_output=False,handle_unknown='ignore',min_frequency=100)
ohe.fit_transform(x_train).shape

(6502, 14)

In [104]:
ohe.get_feature_names_out()

array(['brand_Chevrolet', 'brand_Ford', 'brand_Honda', 'brand_Hyundai',
       'brand_Mahindra', 'brand_Maruti', 'brand_Renault', 'brand_Tata',
       'brand_Toyota', 'brand_Volkswagen', 'brand_infrequent_sklearn',
       'fuel_Diesel', 'fuel_Petrol', 'fuel_infrequent_sklearn'],
      dtype=object)

In [111]:
ohe=OneHotEncoder(sparse_output=False,max_categories=15)
ohe.fit_transform(x_train).shape

(6502, 19)

In [112]:
ohe.get_feature_names_out()

array(['brand_BMW', 'brand_Chevrolet', 'brand_Ford', 'brand_Honda',
       'brand_Hyundai', 'brand_Jaguar', 'brand_Mahindra', 'brand_Maruti',
       'brand_Nissan', 'brand_Renault', 'brand_Skoda', 'brand_Tata',
       'brand_Toyota', 'brand_Volkswagen', 'brand_infrequent_sklearn',
       'fuel_CNG', 'fuel_Diesel', 'fuel_LPG', 'fuel_Petrol'], dtype=object)

In [114]:
#How to handle unknown category
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

ohe=OneHotEncoder(sparse_output=False,handle_unknown='ignore')
ohe.fit_transform(x_train)
ohe.transform(np.array(['local','Petrol']).reshape(1,2))


/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 1.]])

In [115]:
ohe.inverse_transform(np.array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 1.]).reshape(1,36))

array([[None, 'Petrol']], dtype=object)

## LabelBinarizer

In [116]:
from sklearn.preprocessing import LabelBinarizer
y=['cat','dog','fish','dog','cat']
lb=LabelBinarizer()
y_binarized=lb.fit_transform(y)
print('Binarized labels: \n',y_binarized)
y_original=lb.inverse_transform(y_binarized)
print('Original labels: \n',y_original)

Binarized labels: 
 [[1 0 0]
 [0 1 0]
 [0 0 1]
 [0 1 0]
 [1 0 0]]
Original labels: 
 ['cat' 'dog' 'fish' 'dog' 'cat']


# MultiLabelBinarizer

In [117]:
from sklearn.preprocessing import MultiLabelBinarizer

y=[('red','blue'),('blue','green'),('green',),('red',)]
mlb=MultiLabelBinarizer()
y_binarized=mlb.fit_transform(y)
print('Binarized labels: \n',y_binarized)
print('Class labels:',mlb.classes_)
y_original=mlb.inverse_transform(y_binarized)
print('Original labels: \n',y_original)

Binarized labels: 
 [[1 0 1]
 [1 1 0]
 [0 1 0]
 [0 0 1]]
Class labels: ['blue' 'green' 'red']
Original labels: 
 [('blue', 'red'), ('blue', 'green'), ('green',), ('red',)]
